### PR TITLE
Ready Updates

### LINKED ISSUE #4: missing instruction
`README.md` missing instruction, user need to replace stubs in lines [74-76](https://github.com/auth0-samples/auth0-symfony-php-web-app/blob/master/00-Starter-Seed/app/config/config.yml#L74) of config.yml file

### PR DESCRIPTION
**Pull request by iannyanes**
Fixes #4

### CODE REVIEW

**Comment by mpaktiti** [comment]
@chenkie Can you please have someone review this? Thanks.

**Comment by glena** [comment]
Where does the `.env` configuration comes from?

I guess that does not work, did you test it?

it should be configured here https://github.com/auth0-samples/auth0-symfony-php-web-app/blob/master/00-Starter-Seed/app/config/config.yml#L69-L77

as explained in the quickstart https://auth0.com/docs/quickstart/webapp/symfony#5-configure-the-resource-owner

**Comment by mpaktiti** [comment]
^ @iannyanes

**Comment by camimonse** [comment]
The formal issue is this #12

**Pull request closed without merging**
